# permissions for end users to edit edgeworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgeworkload-editor-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeworkloads/status
  verbs:
  - get
