# permissions for end users to view edgedevicesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedeviceset-viewer-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedevicesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedevicesets/status
  verbs:
  - get
