# permissions for end users to view edgedevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgedevice-viewer-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgedevices/status
  verbs:
  - get
