# permissions for end users to view edgeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgeconfig-viewer-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - edgeconfigs/status
  verbs:
  - get
