# permissions for end users to view playbookexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playbookexecution-viewer-role
rules:
- apiGroups:
  - management.project-flotta.io
  resources:
  - playbookexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.project-flotta.io
  resources:
  - playbookexecutions/status
  verbs:
  - get
