// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransmitInfo transmit info
//
// swagger:model transmit_info
type TransmitInfo struct {

	// code rate
	CodeRate string `json:"code_rate,omitempty"`

	// frequency
	Frequency string `json:"frequency,omitempty"`

	// polarization inversion
	PolarizationInversion string `json:"polarization_inversion,omitempty"`

	// power
	Power string `json:"power,omitempty"`

	// spreading factor
	SpreadingFactor string `json:"spreading_factor,omitempty"`
}

// Validate validates this transmit info
func (m *TransmitInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transmit info based on context it is used
func (m *TransmitInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransmitInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransmitInfo) UnmarshalBinary(b []byte) error {
	var res TransmitInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
